### ISSUE TITLE
Missing Tunnels

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#786]
![junk](https://cloud.githubusercontent.com/assets/1422186/13091809/c5350b00-d4b1-11e5-92b4-b032362adc66.jpg)

In the attached bitmap, which is in Berlin, Germany, a tunnel is missing. The upper rendering is with Atlas Beta, using the latest Berlin map downloaded from the mapsforge server. The bottom rendering is from openstreetmap.org. Notice in the bottom rendering, there is a tunnel labeled "Tunnel Ortsteil Britz." It is missing from the Mapsforge rendering. I have not yet investigated whether it is an issue with missing data or with the built-in OSMARENDER theme, pending finding out if this is a known issue or not.

**Comment by lincomatic** [comment]
I did a bit of debugging, and the missing ways are in the map, and get loaded into memory. But I'm not sure why they don't get rendered. Tags are highway=motorway, tunnel=yes and the renderthemes seem to handle this combination.

**Comment by devemux86** [comment]
See also the related forum conversation [here](https://groups.google.com/forum/#!topic/mapsforge-dev/97bAnv0KYHo).

*BTW the Beta versions are not maintained anymore. Please use the regular versions which follow the `dev` branch.*

**Comment by devemux86** [comment]
Rebuilding the map with fresh data (e.g. from Geofabrik) the tunnels appear (screenshot).
(the maps in our server will need to complete their update cycle)

![tunnels](https://cloud.githubusercontent.com/assets/3484020/13103537/c0e27034-d55f-11e5-99e3-c5ae80dbd3b4.png)

**Comment by lincomatic** [comment]
I was not aware of the discussion on the list. Thank you for pointing it out. I'm a bit puzzled by your render above. Why is only a small chunk of the tunnel visible? I downloaded the Berlin map from openandromaps, and it renders the full tunnel, as depicted below:

![image2](https://cloud.githubusercontent.com/assets/1422186/13126035/c05c7d94-d57d-11e5-8852-5abd36d852ce.jpg)

As conjectured by Sebastian Dambeck in the linked discussion, the problem seems to be related to the handling of layers. Debugging MapFile.processWays(), in the openandromaps file, layer = 7 for the tunnel links. In the map downloaded from the Mapsforge server, layer = 4. I don't know why they aren't rendered when layer = 4, but if I force them to layer = 7, then they render correctly.

I also downloaded the latest OSM file from geofabrik, and just like on openstreetmaps.org, layer = -1 for the tunnel links.

So the questions I have are:
1) has anything changed in the mapwriter recently that would affect the handling of layer encoding? I am puzzled as to why the openandromaps map has layer = 7, while the map that I generated myself and the one from your server both have layer = 4.
2) Why don't the tunnels render with layer = 4?

And reviewing the Mapsforge Binary Format spec, actually, layer = 4 is the correct value, because layer is stored as layer+5 to avoid negative values. So there are possibly two bugs at work here:
1) the tunnel should render correctly with layer = 4 (which is really -1)
2)  The mapwriter that openandromaps uses and possibly the one that you're using is incorrectly  writing layer = 7 instead of layer = 4, which cancels out the first bug.

Can you upload your berlin.map somewhere so I can download an analyze the layer that your mapwriter is outputting?

**Comment by applantation** [comment]
Tunnels probably obscured by white land layer.

**Comment by lincomatic** [comment]
If that’s the case, we need to fix this because according to OSM documentation:

“Negative values do not imply that object is underground, use  <http://wiki.openstreetmap.org/wiki/Key:location> location= <http://wiki.openstreetmap.org/w/index.php?title=Tag:location%3Dunderground&action=edit&redlink=1> underground for this purpose.”

**Comment by lincomatic** [comment]
The problem is indeed the layer ordering. The tunnels show up when we draw only layer 4:
![image5](https://cloud.githubusercontent.com/assets/1422186/13130925/1dac0400-d59d-11e5-85d0-d8ded8f9736f.jpg)
But they are obscured by layer 5:
![image4](https://cloud.githubusercontent.com/assets/1422186/13130951/47a1f5b2-d59d-11e5-8ca2-12036177ea89.jpg)
Note that the code erroneously assigns all of the land features to layer 5 (OSM layer 0). They should instead be assigned to a layer that's below layer 0 (OSM layer -5).

**Comment by devemux86** [comment]
I used the official `dev` map-writer with pbf from Geofabrik, but without adding sea / nosea layers, that's why probably the tunnels appear at the start.

**Comment by devemux86** [comment]
> Note that the code erroneously assigns all of the land features to layer 5 (OSM layer 0). They should instead be assigned to a layer that's below layer 0 (OSM layer -5).

It seems the sea rectangle has the right layer [value](https://github.com/mapsforge/mapsforge-mapcreator/blob/master/landextraction.py#L98).
So we need to fix the land coastline? It can be done in map-writer during tag parsing or better setting the proper layer value in land extraction.

**Comment by lincomatic** [comment]
I've been trying to figure out where the code is located that sets the layer for the land features that don't contain a layer tag. Is it in the map writer, or is it assigned on the fly in the reader? I've been perusing the map writer code extensively, and can't locate a function which assigns layers when no layer tag is present.

**Comment by devemux86** [comment]
It's in [OSMUtils.extractSpecialFields](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map-writer/src/main/java/org/mapsforge/map/writer/util/OSMUtils.java#L97).

**Comment by lincomatic** [comment]
Actually, there should be no layer tag at all. See

http://wiki.openstreetmap.org/wiki/Key:layer

layers just relative z levels to handle overlap.

When there is no overlap, no layer tag should be assigned.

**Comment by lincomatic** [comment]
That is where the handling of the layer tag occurs.

Where is the code that assigns layers to features that don’t contain a layer tag?

**Comment by devemux86** [comment]
> Where is the code that assigns layers to features that don’t contain a layer tag?

That method extracts the tags (`layer` parsing is [here](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map-writer/src/main/java/org/mapsforge/map/writer/util/OSMUtils.java#L188-L199)).
By default [layer=5](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map-writer/src/main/java/org/mapsforge/map/writer/util/OSMUtils.java#L101) (OSM value 0) unless the element contains the tag.

**Comment by ludwigb** [comment]
That is also my understanding: the land layer gets layer 0 by default
(mapsforge 5), so everything below it will be blanked out.
Probably a better way will be to assign -5 to it and make sure it gets
rendered after the sea.

Ludwig

**Comment by devemux86** [comment]
+1
See also Christian's [answer](https://groups.google.com/d/msg/mapsforge-dev/97bAnv0KYHo/wP_EdZ3fFgAJ) in forum.

**Comment by devemux86** [comment]
> Probably a better way will be to assign -5 to it and make sure it gets rendered after the sea.

Meaning adding the layer tag in `shape2osm.py` [fixed tags](https://github.com/mapsforge/mapsforge-mapcreator/blob/master/shape2osm.py#L41-L43).

**Comment by ludwigb** [comment]
Yes.

**Comment by devemux86** [comment]
I tested the `layer=-5` in our map creation process with `shape2osm.py`, indeed the problem seems disappearing that way.

So I pushed the needed [change](https://github.com/mapsforge/mapsforge-mapcreator/issues/7) in our map creator repository.

**Comment by ludwigb** [comment]
ok, i will install this on our server soon.

**Comment by lincomatic** [comment]
Sorry, I don't understand how assigning OSM layer = -5 to k="natural", v="nosea" fixes the rendering of the Berlin tunnel. There are several other land layers drawn, as can be seen from the screenshots above. As a test, I added code to MapFile.java to change the layer of k="natural", v="nosea" from 5 to 0, and the tunnel still doesn't render. Am I missing something else?

**Comment by devemux86** [comment]
The rendering follows the `layer` tag (if exist) and the rules z-order inside the render theme (though probably it'd be better having only the last). So the `nosea` polygon with the old default layer=0 (mapsforge 5) was hiding it (and all other negatives).

Note that not all land layers have the `layer` tag, so they appear normally on top of `nosea` following the render theme z-order, as `nosea` is declared 2nd (after `sea`) in render theme list for that purpose.

I attach 3 screenshots of the same area:
1. Multilingual [berlin.map](http://download.mapsforge.org/maps/multilingual/europe/germany/berlin.map) (2016-01-31) which is not rebuilt yet with the fix.
2. Normal [berlin.map](http://download.mapsforge.org/maps/europe/germany/berlin.map) (2016-02-28) which is build with the fix.
3. OpenAndroMaps [berlin.map](http://www.openandromaps.org/maps/Germany/berlin.zip) (2016-02-10) with Osmarender.

The tunnels appear at the voids on 2nd map from our server. That's because we haven't put them above e.g. roads or parks in render theme z-order. OpenAndroMaps (see [forum](https://groups.google.com/d/msg/mapsforge-dev/97bAnv0KYHo/P6u2fDFdFwAJ)) in 3rd map shows the tunnels dashed above other elements.

![1](https://cloud.githubusercontent.com/assets/3484020/13487330/bd6dc55c-e121-11e5-922a-e380d9449ab5.png)
![2](https://cloud.githubusercontent.com/assets/3484020/13487332/c145eb82-e121-11e5-9aad-015c4dab0b91.png)
![3](https://cloud.githubusercontent.com/assets/3484020/13487451/b788440e-e122-11e5-80b2-899be7682486.png)

**Comment by devemux86** [comment]
I think we can close this as the maps behave again as before.

For further showing the tunnels, changes may be needed in their `layer` or render themes.

**Comment by lincomatic** [comment]
Hmm... an unrelated issue I just noticed... if you look at my screenshots above.. two of the green polygons near the center of the map have issues... note the white triangular bits.

![47a1f5b2-d59d-11e5-8ca2-12036177ea89](https://cloud.githubusercontent.com/assets/1422186/13798790/c6da34cc-ead6-11e5-965e-52794b6545c3.jpg)

**Comment by devemux86** [comment]
Probably related to  #633 or #586 ?

**Comment by lincomatic** [comment]
I think it may be related to tag mapping . I just downloaded the Berlin map from OpenAndroMaps, and it doesn't have the error. However, it is not the same problem as [#586](https://github.com/mapsforge/mapsforge/issues/586), because I don't see force-polygon-line=true for cemetary in the tag_mapping.xml

**Comment by lincomatic** [comment]
OK I did more research. Using tag mapping from OpenAndroMaps didn't help. So I looked inside their Berlin.map and found that they used map-writer-0.3.0. So I generated the Berlin map using 0.3.0, and the problem goes away! I am going to open a new bug for this

**Comment by lincomatic** [comment]
See [#795](https://github.com/mapsforge/mapsforge/issues/795)
